
deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  before_script:
    - apt update
    - apt install -y curl docker.io
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    - nvm install 14
  script:
    - npm install
    - npx prisma migrate deploy
    - aws ecr get-login --no-include-email
    # - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com
    - docker build --tag unboxing-server:latest .
    - docker tag unboxing-server:latest 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com/unboxing-server:latest
    - docker push 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com/unboxing-server:latest
