variables:
  DOCKER_REGISTRY: 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com

deploy:
  stage: deploy
  image: 
    name: sleavely/node-awscli:14.x
    entrypoint: [""]
  before_script:
    - aws --version
    - apt update
    - apt install -y docker.io
    # - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    # - export NVM_DIR="$HOME/.nvm"
    # - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    # - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    # - nvm install 14
    # - mkdir ~/.aws
    # - echo "[default]" >> ~/.aws/credentials
    # - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    # - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  script:
    - npm install
    - npx prisma migrate deploy
    # - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    # - docker login -u AWS -p $(aws ecr get-login-password  --region ap-northeast-2) 120032305088.dkr.ecr.the-region-you-are-in.amazonaws.com
    - docker build --tag unboxing-server:latest .
    - docker tag unboxing-server:latest 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com/unboxing-server:latest
    - docker push 120032305088.dkr.ecr.ap-northeast-2.amazonaws.com/unboxing-server:latest
